language: java
jdk: openjdk7
install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd ..
  - git clone https://github.com/aerogear/aerogear-unifiedpush-server.git
script: mvn -f aerogear-unified-push-server-admin-ui-tests/pom.xml test
